@extends('layouts.app')
@section('content')
<section class="hero">
    <div class="hero-media"><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2000&q=85" alt="Équipe technologique dans un espace de travail moderne"></div><div class="hero-overlay"></div>
    <div class="container hero-content"><p class="eyebrow light">Conseil · Réseaux · Solutions digitales</p><h1>Des services informatiques qui font avancer votre activité.</h1><p>TNTMTECH conçoit, déploie, sécurise et maintient les environnements numériques des entreprises et institutions.</p><div class="button-row"><a class="btn btn-primary" href="{{ route('services.index') }}">Découvrir nos services</a><a class="btn btn-light" href="{{ route('quote') }}">Demander un devis</a></div><div class="hero-trust"><span><strong>360°</strong> Conseil et suivi</span><span><strong>2 agences</strong> Douala & Yaoundé</span><span><strong>6 expertises</strong> Pour vos projets IT</span></div></div>
</section>
<section class="services-band"><div class="container"><div class="section-heading light"><div><p class="eyebrow light">Nos prestations</p><h2>Une équipe technique à vos côtés</h2></div><p>Nous diagnostiquons, déployons et maintenons les solutions qui soutiennent votre organisation.</p></div><div class="service-grid">@foreach($services as $i => $service)<a class="service-item" href="{{ route('services.show', $service) }}"><span>0{{ $i + 1 }}</span><div><h3>{{ $service->name }}</h3><p>{{ $service->summary }}</p></div><b>↗</b></a>@endforeach</div></div></section>
<section class="section value-section"><div class="container value-grid"><div><p class="eyebrow">Pourquoi TNTMTECH</p><h2>Des choix techniques clairs. Un suivi réellement local.</h2><p>Nous partons de vos usages et de vos contraintes pour construire une solution fiable, documentée et simple à exploiter.</p><a class="text-link" href="{{ route('page', 'entreprise') }}">Découvrir notre approche →</a></div><div class="value-points"><article><strong>01</strong><h3>Diagnostic</h3><p>Une compréhension précise de votre environnement.</p></article><article><strong>02</strong><h3>Conception</h3><p>Des recommandations adaptées à vos objectifs.</p></article><article><strong>03</strong><h3>Déploiement</h3><p>Une mise en œuvre maîtrisée et documentée.</p></article><article><strong>04</strong><h3>Assistance</h3><p>Un accompagnement local dans la durée.</p></article></div></div></section>
<section class="cta-band"><div class="container"><div><p class="eyebrow light">Un besoin précis ?</p><h2>Construisons la solution adaptée à votre organisation.</h2></div><a class="btn btn-light" href="{{ route('quote') }}">Demander un devis</a></div></section>
@endsection
