@extends('layouts.app')
@section('title', $service->name.' — TNTMTECH')
@section('content')
<section class="service-hero"><div class="container"><div><p class="eyebrow light">{{ $service->eyebrow }}</p><h1>{{ $service->name }}</h1><p>{{ $service->summary }}</p><div class="button-row"><a class="btn btn-primary" href="{{ route('quote', ['service' => $service->slug]) }}">Demander un devis</a><button class="btn btn-light" data-service-whatsapp-open>Demander ce service</button></div></div>@if($service->image)<img src="{{ $service->image }}" alt="{{ $service->name }}">@endif</div></section>
<section class="section container two-columns"><div><p class="eyebrow">Notre intervention</p><h2>Une méthode lisible, des résultats durables</h2><p class="lead">{{ $service->description }}</p></div><div class="deliverables"><h3>Ce que nous livrons</h3>@foreach($service->deliverables ?? [] as $item)<div><span>✓</span><p>{{ $item }}</p></div>@endforeach</div></section>
<section class="process-band"><div class="container"><p class="eyebrow">Notre méthode</p><h2>Du diagnostic au transfert de compétences</h2><div class="process-grid">@foreach(['Diagnostic de votre environnement','Recommandation claire et chiffrée','Déploiement documenté','Formation et suivi'] as $i => $step)<div><span>0{{ $i+1 }}</span><h3>{{ $step }}</h3></div>@endforeach</div></div></section>
<dialog class="agency-dialog" data-service-whatsapp-dialog><button class="dialog-close" data-service-whatsapp-close aria-label="Fermer">×</button><p class="eyebrow">Demander ce service</p><h2>Choisissez votre agence</h2><div class="agency-list">@foreach($agencies as $agency)<a target="_blank" rel="noopener" href="https://wa.me/{{ $agency['whatsapp'] }}?text={{ rawurlencode('Bonjour TNTMTECH, je suis intéressé(e) par le service « '.$service->name.' ». Je souhaite échanger avec votre équipe à ce sujet.') }}"><strong>{{ $agency['name'] }}</strong><span>{{ $agency['phone'] }}</span></a>@endforeach</div></dialog>
@push('scripts')<script>document.querySelector('[data-service-whatsapp-open]')?.addEventListener('click',()=>document.querySelector('[data-service-whatsapp-dialog]')?.showModal());document.querySelector('[data-service-whatsapp-close]')?.addEventListener('click',()=>document.querySelector('[data-service-whatsapp-dialog]')?.close());</script>@endpush
@endsection
